meta:
  url: https://sdran-simulator.dhanifudin.com
  title: SDRAN Simulator
  description:
  siteName: SDRAN Simulator
  sns: ['github']
slide:
  loop: false
  ui:
    sidebar: true
    vertical: false
    pagination: progressbar # bullets | progressbar | fraction
    effect: # fade | cube | flip
  code:
    # https://prismjs.com/
    plugins: []
    theme: default # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
